### ISSUE TITLE
Create moodboard

### ISSUE THREAD

**Issue by nickbytes** [kamp-group/website#2]
![image](https://user-images.githubusercontent.com/3009331/55499677-97586c80-5614-11e9-85df-61124b16440f.png)
 plz hurry

**Comment by urcades** [comment]
Sir, 

*salutes*

The "Editorial Inspo" drop point has been established: 
 
https://www.are.na/edouard-urcades/editorial-inspo-uyxobhzegrm

Sir, I'm not sure why the url slug is totally FUCKED up, I will contact Cab about this.
