### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by urcades** [kamp-group/website#3]
![kamp](https://user-images.githubusercontent.com/1195363/55501739-0b950f00-5619-11e9-8c53-6ed7a0487333.png)

Logo Concept, Please Critique

**Comment by ishakasliwal** [comment]
i like this a lot

what if the right side of the m went to the middle of the P

**Comment by urcades** [comment]
Ya forget the above —

![large_b01d1ec8b2f0c8f05951bb6bd6f7074f](https://user-images.githubusercontent.com/1195363/55523228-276ad600-5656-11e9-9d85-38d6cad671f1.png)

— earthperson blew this one out of the water, we can additionally keep to @morgane 's idea to keep the K and A more or less static while the A and M are represented w/ more dynamism

**Comment by nickbytes** [comment]
Closing this, since we decided on a logo.
